services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_PORT
        fromSecret: DB_PORT
      - key: DB_NAME
        fromSecret: DB_NAME
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: PORT
        value: 8000
